---
title: "My Sales Overview"
output: 
  flexdashboard::flex_dashboard:
    css: style.css
    orientation: rows

---

```{r}
# Libraries -------------------------------------------------------------------
library(flexdashboard)
library(tidyverse)
library(DBI)
library(odbc)
library(DT)
library(warehouse)
library(dbplyr)
library(plotly)
library(lubridate)
library(scales)
library(sunburstR)
library(d3r)


# Connect to RStudio Warehouse ----------------------------------------------------
con <- DBI::dbConnect(odbc::odbc(), database = "marketing", 
                      Driver = "Redshift",
                      host = "redhouse.cyii7eabibhu.us-east-1.redshift.amazonaws.com", 
                      port = "5439", UID = "rjohnson", PWD = Sys.getenv("WAREHOUSE_PASSWORD"))


# Gather Accounts, Opps, and Partner info -----------------------------------------
opps <- tbl(con, in_schema("salesforce", "opportunity")) %>% collect()
acct <- tbl(con, in_schema("salesforce", "account")) %>% collect()
partners <- tbl(con, in_schema("salesforce", "account_partner")) %>% collect()

## My personal ownerId
rj_ownerId <- "0050L000009iXh7QAE"


# Data Processing for Dashboard -------------------------------------------------------
## Filter for my opps
rj_opps <- opps %>% 
  filter(is_deleted == 0) %>% 
  filter(owner_id == rj_ownerId) %>% 
  filter(type == "Renewal") %>% 
  select(id, account_id, name, amount, stage_name, probability, created_date, close_date, 
         type, forecast_category, forecast_category_name, lead_source, description, 
         last_activity_date, fiscal_quarter, fiscal_year, fiscal) %>% 
  rename(opp_id = id,
         opp_name = name,
         opp_amount = amount,
         opp_stage = stage_name,
         opp_created_date = created_date,
         opp_close_date = close_date,
         opp_description = description,
         opp_last_activity = last_activity_date,
         opp_fiscal_year = fiscal_year,
         opp_fiscal_quarter = fiscal_quarter)

## Filter for my accounts
rj_acct <- acct %>% 
  filter(is_deleted == 0) %>% 
  filter(owner_id == rj_ownerId) %>% 
  select(id, name, type, billing_street, billing_city, billing_state, billing_country,
         shipping_city, shipping_state, shipping_country, industry, last_activity_date) %>% 
  rename(account_id = id,
         account_name = name,
         account_type = type,
         account_last_activity = last_activity_date)

## Add partners to accounts (maybe add later)
# partner_id_name <- partners %>%
#   filter(role == "Reseller") %>% 
#   rename(account_id = account_from_id,
#          partner_id = account_to_id)  %>% 
#   left_join(acct, by = c("partner_id" = "id")) %>% 
#   select(account_id, partner_id, name) %>% 
#   rename(partner_name = name) %>% 
#   unique()

  
## Add account names to opps
rj_opps_acct <- rj_opps %>% 
  left_join(rj_acct, by = "account_id") %>% 
  select(opp_id, account_id, account_name, opp_name, opp_amount, opp_stage,
         probability, opp_created_date, opp_close_date, everything())

## Set today date
today <- Sys.Date()

## Extract tasks associated with me
tasks <- tbl(con, in_schema("salesforce", "task"))

rj_tasks <- tasks %>% 
  filter(owner_id == rj_ownerId,
         status != "Completed") %>% 
  select(id, account_id, what_id, subject, description, activity_date, type) %>% 
  rename(task_id = id,
         task_subject = subject,
         task_description = description,
         task_date = activity_date,
         task_type = type) %>% 
  collect()

## Create Account and Opp Id dictionary
acct_id_dictionary <- rj_acct %>% 
  select(account_id, account_name) %>% 
  unique()

opp_id_dictionary <- rj_opps %>% 
  select(opp_id, opp_name) %>% 
  unique()

acct_opp_dictionary <- tibble(id = c(rj_acct$account_id, rj_opps$opp_id),
                              name = c(rj_acct$account_name, rj_opps$opp_name))








# Plots / Tables for Dashboard ---------------------------------------------------
acct_url_pre <- '<a href="https://na39.lightning.force.com/lightning/r/Account/'
opp_url_pre  <- '<a href="https://na39.lightning.force.com/lightning/r/Opportunity/'
task_url_pre <- '<a href="https://na39.lightning.force.com/lightning/r/Task/'

## Opp Table
days_breaks <- c(7, 14, 30, 45, 90)
color_breaks <- rev(c('#ffffb2','#fed976','#feb24c','#fd8d3c','#f03b20','#bd0026'))

rj_opps_table <- rj_opps_acct %>% 
  filter(!opp_stage %in% c("Closed Won", "Closed Lost")) %>% 
  select(opp_id, account_id, account_name, opp_name, opp_amount, opp_stage, opp_close_date,
         opp_last_activity, account_last_activity) %>% 
  # Make account and opps urls
  mutate(Account = paste0(acct_url_pre, account_id, '/view">', account_name, '</a>')) %>% 
  mutate(Opportunity = paste0(opp_url_pre, opp_id, '/view">', opp_name, '</a>')) %>% 
  # Calculate days to close
  mutate(`Days to Close` = as.double(difftime(ymd(opp_close_date),
                                              ymd(today),
                                              units = "days"))) %>% 
  select(Account, Opportunity, opp_stage, opp_amount, opp_close_date, `Days to Close`) %>% 
  rename(`Opp Amount` = opp_amount,
         `Opp Stage` = opp_stage,
         `Close Date` = opp_close_date) %>% 
  unique() %>% 
  arrange(`Days to Close`)


## Task Table
rj_task_table <- rj_tasks %>%
  filter(!is.na(task_id)) %>% 
  select(task_id, account_id, task_date, 
         task_subject, task_description, task_type) %>%
  left_join(acct_id_dictionary, by = "account_id") %>% 
  # Make account and task urls
  mutate(Account = paste0(acct_url_pre, account_id, '/view">', account_name, '</a>')) %>% 
  mutate(Task = paste0(task_url_pre, task_id, '/view">', task_subject, '</a>')) %>% 
  # Calculate days until task is due
  mutate(`Days until Due` = as.double(difftime(ymd(task_date),
                                               ymd(today),
                                               units = "days"))) %>% 
  select(Account, Task, `Days until Due`) %>% 
  arrange(`Days until Due`)


## Sales Prediction Plot
fiscal_year <- 2020
fiscal_quarter <- 2

rj_sales_data <- rj_opps_acct %>% 
  select(opp_id, opp_stage, opp_close_date, opp_amount, opp_fiscal_year, opp_fiscal_quarter) %>% 
  mutate(opp_stage = ifelse(opp_stage %in% c("Evaluation", "Quoted"), "Open", opp_stage)) %>% 
  filter(opp_fiscal_year == fiscal_year & opp_fiscal_quarter == fiscal_quarter)

min_date <- min(rj_sales_data$opp_close_date)
  

rj_sales_data2 <- rj_sales_data %>% 
  # Add columns to initialize each stage as $0
  add_row(opp_id = LETTERS[1:3],
          opp_stage = c("Closed Lost", "Closed Won", "Open"),
          opp_close_date = min_date,
          opp_amount = 0) %>%
  arrange(opp_close_date) %>% 
  group_by(opp_stage) %>% 
  mutate(group_totals = cumsum(opp_amount)) %>% 
  ungroup() %>% 
  pivot_wider(id_cols = c(opp_id, opp_close_date, opp_fiscal_year, opp_fiscal_quarter), 
              names_from = opp_stage,
              values_from = group_totals, 
              values_fill = list(group_totals = 0)) %>% 
  mutate(`Won Total` = cumsum(`Closed Won`)) %>%
  mutate(`Lost Total` = cumsum(`Closed Lost`)) %>% 
  mutate(`Open Total` = cumsum(Open)) %>% 
  mutate(`All Opps` = `Won Total` + `Lost Total` + `Open Total`) %>% 
  mutate(Churn = ifelse(opp_close_date > Sys.Date(), NA, `Won Total` + `Lost Total`)) %>% 
  mutate(Winnings = ifelse(opp_close_date > Sys.Date(), NA, `Won Total`))




## Sunburst Plot
rj_sunburst_table <- rj_opps_acct %>% 
  filter(!opp_stage %in% c("Closed Won", "Closed Lost")) %>% 
  select(opp_id, account_id, account_name, opp_name, opp_amount, opp_stage, opp_close_date,
         opp_last_activity, account_last_activity) %>% 
  # Calculate days to close
  mutate(days_to_close = as.double(difftime(ymd(opp_close_date),
                                            ymd(today),
                                            units = "days"))) %>% 
  select(account_name, opp_name, opp_stage, opp_amount, opp_close_date, days_to_close) %>% 
  unique() %>% 
  arrange(days_to_close) %>% 
  mutate(opp_name_days = paste0(opp_name, " -- Days to close: ", days_to_close)) %>% 
  select(account_name, opp_name_days, opp_amount, opp_stage, days_to_close)

# Get list of ALL calls, past and present
# Does not include in person meetings
all_calls <- tasks %>% 
  filter(task_subtype == "Call", type == "Call") %>% 
  filter(is_deleted == "0") %>% # This line is weird and could cause problems
  filter(status == "Completed") %>%
  select(id, account_id, what_id, activity_date,
         subject, description, status,
         who_id, owner_id) %>%
  collect()

# merge calls into accounts
calls_account <- rj_acct %>% 
  left_join(all_calls, by = "account_id") %>% 
  select(account_name, activity_date) %>% 
  # Calculate days from last call
  mutate(days_last_call = as.double(difftime(ymd(today),
                                             ymd(activity_date),
                                             units = "days"))) %>% 
  group_by(account_name) %>% 
  filter(days_last_call == min(days_last_call) | is.na(days_last_call)) %>% 
  unique() %>% 
  ungroup() %>% 
  mutate(account_name_days = paste0(account_name, " -- Days since last call: ", days_last_call))

# Add to sunburst table and change account name
rj_sunburst_table_call <- rj_sunburst_table %>% 
  left_join(calls_account, by = "account_name") %>% 
  select(account_name_days, everything()) %>% 
  select(-account_name)

# Add colors conditionally
calls_account_color <- calls_account %>% 
  mutate(acct_color = ifelse(days_last_call <= 90, "#0571b0",
                      ifelse(days_last_call > 90 & days_last_call <= 180, "#92c5de",
                      ifelse(days_last_call > 180 & days_last_call <= 270, "#f4a582", 
                             "#ca0020")))) %>% 
  mutate(acct_color = ifelse(is.na(acct_color), "#ca0020", acct_color))

# Color opps by days to close
opps_color <- rj_sunburst_table_call %>% 
  select(opp_name_days, days_to_close) %>% 
  mutate(opp_color = ifelse(days_to_close <= 0, "#b10026",
                     ifelse(days_to_close > 0 & days_to_close <= 7, "#e31a1c",
                     ifelse(days_to_close > 7 & days_to_close <= 14, "#fc4e2a",
                     ifelse(days_to_close > 14 & days_to_close <= 21, "#fd8d3c",        
                     ifelse(days_to_close > 21 & days_to_close <= 45, "#feb24c",
                     ifelse(days_to_close > 45 & days_to_close <= 90, "#fed976", 
                     "#a1d99b")))))))

```



Summary
=======================================================================
Row
-----------------------------------------------------------------------

### Accounts {.value-box}
```{r}
valueBox(value = nrow(rj_acct), 
         caption = "Total Accounts", 
         icon = "fa-building", 
         color = "#7f8de1")
```


### Opps {.value-box}
```{r}
valueBox(value = nrow(rj_opps_table), 
         caption = "Total Opps", 
         icon = "fa-crown", 
         color = "#f9b95b")
```

### Tasks {.value-box}
```{r}
valueBox(value = nrow(rj_task_table), 
         caption = "Tasks Due", 
         icon = "fa-tasks", 
         color = "#4bc076")
```

Row
-----------------------------------------------------------------------

### Sales Data

```{r}
sales_plot <- rj_sales_data2 %>%
  ggplot(aes(x = opp_close_date)) +
  # Totals
  geom_line(aes(y = `All Opps`)) +
  geom_point(aes(y = `All Opps`)) +
  # Churn
  geom_line(aes(y = Churn), color = "red") +
  geom_point(aes(y = Churn), color = "red") +
  # Winnings
  geom_line(aes(y = Winnings), color = "blue") +
  geom_point(aes(y = Winnings), color = "blue") +
  scale_y_continuous(labels = dollar)

ggplotly(sales_plot)
```



### Company Opp Amounts

```{r}
sunburst_tree <- rj_sunburst_table_call %>% 
  select(account_name_days, opp_name_days, opp_amount) %>% 
  d3_nest(value_cols = "opp_amount")

my_colors <- list(range = c(calls_account_color$acct_color, opps_color$opp_color),
                  domain = c(calls_account_color$account_name_days, opps_color$opp_name_days))

sunburst_opps <- sund2b(sunburst_tree, 
                        valueField = "opp_amount", 
                        colors = my_colors, 
                        rootLabel = "All Open Opps", 
                        width = "100%",
                        breadcrumbs = sund2bBreadcrumb(enabled = FALSE))
sunburst_opps
```


Row
-----------------------------------------------------------------------

### Chart 3

```{r}

```



### Chart 4

```{r}

```


Opportunities
===============================================

### Opportunities

```{r}
DT::datatable(rj_opps_table, escape = FALSE) %>% 
  formatStyle(columns = "Days to Close",
              backgroundColor = styleInterval(days_breaks, color_breaks)) %>% 
  formatCurrency(columns = "Opp Amount", currency = "$")
```


Tasks
===============================================

### Tasks

```{r}
DT::datatable(rj_task_table, escape = FALSE) %>% 
  formatStyle(columns = "Days until Due",
              backgroundColor = styleInterval(days_breaks, color_breaks))
```
